/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tritonus_lowlevel_alsa_AlsaSeqQueueTimer */

#ifndef _Included_org_tritonus_lowlevel_alsa_AlsaSeqQueueTimer
#define _Included_org_tritonus_lowlevel_alsa_AlsaSeqQueueTimer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tritonus_lowlevel_alsa_AlsaSeqQueueTimer
 * Method:    malloc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_alsa_AlsaSeqQueueTimer_malloc
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_alsa_AlsaSeqQueueTimer
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_alsa_AlsaSeqQueueTimer_free
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_alsa_AlsaSeqQueueTimer
 * Method:    getQueue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_alsa_AlsaSeqQueueTimer_getQueue
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_alsa_AlsaSeqQueueTimer
 * Method:    getType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_alsa_AlsaSeqQueueTimer_getType
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_alsa_AlsaSeqQueueTimer
 * Method:    getResolution
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_alsa_AlsaSeqQueueTimer_getResolution
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_alsa_AlsaSeqQueueTimer
 * Method:    setType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_alsa_AlsaSeqQueueTimer_setType
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tritonus_lowlevel_alsa_AlsaSeqQueueTimer
 * Method:    setResolution
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_alsa_AlsaSeqQueueTimer_setResolution
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
