/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tritonus_lowlevel_alsa_AlsaSeq_QueueTimer */

#ifndef _Included_org_tritonus_lowlevel_alsa_AlsaSeq_QueueTimer
#define _Included_org_tritonus_lowlevel_alsa_AlsaSeq_QueueTimer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tritonus_lowlevel_alsa_AlsaSeq_QueueTimer
 * Method:    malloc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_alsa_AlsaSeq_00024QueueTimer_malloc
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_alsa_AlsaSeq_QueueTimer
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_alsa_AlsaSeq_00024QueueTimer_free
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_alsa_AlsaSeq_QueueTimer
 * Method:    getQueue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_alsa_AlsaSeq_00024QueueTimer_getQueue
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_alsa_AlsaSeq_QueueTimer
 * Method:    getType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_alsa_AlsaSeq_00024QueueTimer_getType
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_alsa_AlsaSeq_QueueTimer
 * Method:    getResolution
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_alsa_AlsaSeq_00024QueueTimer_getResolution
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_alsa_AlsaSeq_QueueTimer
 * Method:    setType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_alsa_AlsaSeq_00024QueueTimer_setType
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tritonus_lowlevel_alsa_AlsaSeq_QueueTimer
 * Method:    setResolution
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_alsa_AlsaSeq_00024QueueTimer_setResolution
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
