/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tritonus_lowlevel_esd_EsdSample */

#ifndef _Included_org_tritonus_lowlevel_esd_EsdSample
#define _Included_org_tritonus_lowlevel_esd_EsdSample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tritonus_lowlevel_esd_EsdSample
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_esd_EsdSample_close
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_esd_EsdSample
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_esd_EsdSample_free
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_esd_EsdSample
 * Method:    kill
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_esd_EsdSample_kill
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_esd_EsdSample
 * Method:    loop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_esd_EsdSample_loop
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_esd_EsdSample
 * Method:    open
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_esd_EsdSample_open
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_tritonus_lowlevel_esd_EsdSample
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_esd_EsdSample_play
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_esd_EsdSample
 * Method:    setVolume
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_esd_EsdSample_setVolume
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_tritonus_lowlevel_esd_EsdSample
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_esd_EsdSample_stop
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_esd_EsdSample
 * Method:    write
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_esd_EsdSample_write
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
