/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tritonus_lowlevel_esd_EsdStream */

#ifndef _Included_org_tritonus_lowlevel_esd_EsdStream
#define _Included_org_tritonus_lowlevel_esd_EsdStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tritonus_lowlevel_esd_EsdStream
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_esd_EsdStream_close
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_esd_EsdStream
 * Method:    open
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_esd_EsdStream_open
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_tritonus_lowlevel_esd_EsdStream
 * Method:    write
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_esd_EsdStream_write
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
